spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:foo;AUTO_SERVER_PORT=9090;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS \"foo\";

  jpa:
     show-sql: false
     hibernate:
       ddl-auto: validate
     properties:
       hibernate.id.new_generator_mappings: false