spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:public;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;INIT=CREATE SCHEMA IF NOT EXISTS \"public\";

  jpa:
     show-sql: false
     hibernate:
       ddl-auto: validate
     properties:
       hibernate.id.new_generator_mappings: false